
SELECT PRODUCT_CODE, IFNULL(SUM(SALES_AMOUNT) * PRICE, 0) AS SALES
FROM PRODUCT P 
LEFT JOIN OFFLINE_SALE O 
ON P.PRODUCT_ID = O.PRODUCT_ID 
GROUP BY PRODUCT_CODE 
ORDER BY SALES DESC, PRODUCT_CODE;

# SELECT * FROM PRODUCT P
# LEFT JOIN OFFLINE_SALE O
# ON P.PRODUCT_ID = O.PRODUCT_ID;