# -- 코드를 입력하세요
# SELECT O.ANIMAL_ID, O.NAME 
# FROM ANIMAL_OUTS O 
# LEFT JOIN ANIMAL_INS I 
# ON O.ANIMAL_ID = I.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL
# ORDER BY O.ANIMAL_ID;

SELECT ANIMAL_ID, NAME FROM ANIMAL_OUTS WHERE ANIMAL_ID NOT IN(SELECT O.ANIMAL_ID FROM ANIMAL_OUTS O INNER JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID);