WITH RECURSIVE number_sequence(HOUR) AS (
	SELECT 0
	UNION ALL
	SELECT HOUR + 1 FROM number_sequence WHERE HOUR < 23
) SELECT HOUR, 0 as COUNT FROM number_sequence
WHERE HOUR NOT IN (SELECT CAST(DATE_FORMAT(DATETIME, '%H') AS SIGNED) AS HOUR FROM ANIMAL_OUTS)
UNION
SELECT CAST(DATE_FORMAT(DATETIME, '%H') AS SIGNED) AS HOUR, COUNT(*)
FROM ANIMAL_OUTS GROUP BY HOUR ORDER BY HOUR;